# AppVeyor Config
# http://www.appveyor.com/docs/lang/nodejs-iojs

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

skip_tags: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version

  # run tests
  - npm run lint
  - npm run mocha

# Don't run MSBuild
build: off
